'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
'''

def Fibonacci_even_valued_terms(n):

    f = [0, 1]
    even_values = 0 


    for i in range(2, n+1):
        f.append(f[i-1] + f[i-2])
        if f[i] % 2 == 0:
            even_values = even_values + f[i]

    return even_values



print(Fibonacci_even_valued_terms(4000000))